### ISSUE TITLE
[ModalDefault]: Content within Modals with sticky footer has no height on IE11

### ISSUE THREAD

**Issue by jichan-thumbtack** [thumbtack/thumbprint#115]
When using `<ModalFooter isSticky>` on IE11, the contents container <div> has `flex: 1` applied. This works expected on narrow viewports but on wide viewports where there is no set height of the parent, it results in an unexpected behavior in which this contents container has no height (except for padding). We probably can just selectively apply this style on narrow viewports? If this sounds good, I can just create a PR

![stickyfooter](https://user-images.githubusercontent.com/40370813/52596795-121bbd00-2e06-11e9-875c-24af43bc820d.gif)

**Comment by danoc** [comment]
Hi @jichan-thumbtack — I think that solution would work.

Here's the relevant code:
https://github.com/thumbtack/thumbprint/blob/master/packages/thumbprint-react/components/ModalDefault/index.module.scss#L123-L125

I think changing it to `flex: 1 1 0%` may also work—although I haven't tested it.

Would love a PR for this!
