### ISSUE TITLE
[@thumbtack/thumbprint-react]: Button with theme caution focus state does not look focused

### ISSUE THREAD

**Issue by xanderwebs** [thumbtack/thumbprint#116]
Hey, this may not be an issue -- I noticed that when placing the caution and secondary buttons together, the focus state on the caution button is extremely subtle.

See:
<img width="654" alt="screen shot 2019-02-12 at 11 21 52 am" src="https://user-images.githubusercontent.com/2138022/52662296-c0803a80-2eb8-11e9-9195-111afa755b79.png">

Compared to when the focus is on the secondary button:
<img width="659" alt="screen shot 2019-02-12 at 11 25 06 am" src="https://user-images.githubusercontent.com/2138022/52662378-e86f9e00-2eb8-11e9-96cd-e33f33750cc1.png">

Wondering if this is intentional.

**Comment by danoc** [comment]
Hi! I believe this was by accident. Thanks for pointing it out. We're working on some tweaks to our buttons, so I'll roll this out as part of that.

**Comment by danoc** [comment]
@jonpkerwin — Should the `danger` button focus status on web (activated when a user tabs onto the button or clicks on it) have a red border to be consistent with the other themes?

**Comment by jonpkerwin** [comment]
Yes. Default is a gray 2px border - active and focused states have a red 2px border. Native documentation is correct if you need a visual there.

**Comment by danoc** [comment]
Sounds good to me. Will make the fix.

**Comment by danoc** [comment]
@xanderwebs — Thanks for flagging. This was merged and will go out in the next release.
