### ISSUE TITLE
Error when using with React 16.8

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#119]
According to the latest package.json, `thumbprint-react@0.2.1` supports `"react": ">= 16.3.2 < 17.0.0-0"`.  However, using React 16.8.1, i get the following error when compiling with Webpack: 

```
TypeError: __chunk_1.inherits is not a function
at Module../node_modules/@thumbtack/thumbprint-react/dist/cjs/components/Avatar/index.jsx
```

**Comment by danoc** [comment]
Weird. Can't imagine why it'd fail. I won't be able to dig into this in the next few days, but happy to accept a PR from anyone interested.

**Comment by danoc** [comment]
@lavelle — Seems to work fine:
https://codesandbox.io/s/9oxm04wvor

Did you get this error _while_ Create React App was running? What happens if you do `yarn install --force` or restart CRA (or whatever flavor of Webpack)?

Will close for now, but LMK if that doesn't fix.
