### ISSUE TITLE
DatePicker React: Remove use of `componentWillReceiveProps`

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#12]
It is deprecated and will be removed from future versions of React.

We will need to rewrite the component. The code is currently difficult to follow and could use some cleaning up.

**Comment by danoc** [comment]
This could be a good opportunity to re-write the component w/ React Hooks, too.

**Comment by lavelle** [comment]
After review, will probably do a larger refactor to make it a fully controlled component. The component currently uses a confusing mix of props and internal state to control the selected days.
