### ISSUE TITLE
DatePicker dependency should be upgraded

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#150]
`DatePicker` currently uses: `6.2.1` of `react-day-picker`. `7.3.0` has some fixes for IE 11.

Though the reported bug in https://thumbtack.atlassian.net/browse/FE-1637 is not due to the Thumbprint component, the problem does exist.

**Comment by danoc** [comment]
Edited the title because it turns out that our version is working in IE. The documentation is broken in IE 11 which is why it looks like the DatePicker is as well. The documentation fix for IE 11 is almost done and being fixed here: https://github.com/thumbtack/thumbprint/pull/154

**Comment by danoc** [comment]
...that said, we probably should still upgrade the `DatePicker`?
