### ISSUE TITLE
Use tabs for documenting the token platforms

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#181]
![image](https://user-images.githubusercontent.com/916038/55027084-a5c5d900-4fc1-11e9-9d00-8555ec4ec5df.png)

We currently use a dropdown which folks have said is hard to find. Using tabs would make it more consistent with our component pages:

![image](https://user-images.githubusercontent.com/916038/55027111-b8401280-4fc1-11e9-8300-889e1040a501.png)

***
Thanks @webbower for pointing this out!

**Comment by benknight** [comment]
Is Tabs an actual component yet?  If so, we'd definitely use it on the Help site.

**Comment by danoc** [comment]
@benknight — It is not. But I imagine it'd be helpful.

cc: @jonpkerwin

**Comment by danoc** [comment]
@webbower — This is now live 🎉
