### ISSUE TITLE
Consider supporting a full bleed ModalDefault

### ISSUE THREAD

**Issue by dcapo** [thumbtack/thumbprint#194]
Currently, ModalDefault has strict ownership of its content's padding. This prevents children from having a full bleed background color, as seen here:

![Storybook](https://user-images.githubusercontent.com/880266/55353069-47906e80-5477-11e9-9725-3a1aa4e33dbb.png)

Maybe we can consider supporting some sort of padding override to allow for this use case?
Designer: johan

**Comment by danoc** [comment]
Sweet, thanks for making this @dcapo.

@jonpkerwin — I'll find you later and give you some context offline.

**Comment by benknight** [comment]
Yes I have also wished for this!

**Comment by danoc** [comment]
Hi! Chatted with @jonpkerwin about this and we're on-board with making it possible for parts of a modal to be full width.

I could imagine an API like this:


```jsx
<ModalDefault>
    <ModalDefaultHeader>
        <ModalDefaultTitle>...</ModalDefaultTitle>
        <ModalDefaultDescription>
            ...
        </ModalDefaultDescription>
    </ModalDefaultHeader>

    <ModalDefaultContent>
        <p>Content that has padding</p>

        <ModalDefaultContentFullBleed>
            This content is now full bleed.
        </ModalDefaultContentFullBleed>

        <p>This content has padding</p>
    </ModalDefaultContent>

    <ModalDefaultFooter>
        ...
    </ModalDefaultFooter>
</ModalDefault>
```

Thoughts? We'd need to prototype, but I think this can make that design work.

**Comment by benknight** [comment]
Maybe `<ModalDefaultContent isFullBleed />`

**Comment by benknight** [comment]
I have a PR for this, I'm just waiting for repo access.

**Comment by danoc** [comment]
Whoever works on this should check out the discussion in #217 for additional context on the problem and possible solutions.

**Comment by danoc** [comment]
@lavelle — I'll be in at 11:45 today. This would be a good quick task if you'd like something small before our `Avatar` sync.

**Comment by danoc** [comment]
This is in progress at #269. 

cc: @senseiurata since it's relevant to the DatePicker migration.
