### ISSUE TITLE
Improve example for applying bold style on links

### ISSUE THREAD

**Issue by senseiurata** [thumbtack/thumbprint#211]
For applying _any_ bold font-weight to text, I think we should prefer to use the `b` atomic class unless we intend to use the [strong tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong) from a content perspective. I feel like the example encourages using `strong` for styling purposes.

https://thumbprint.design/components/link/react/#example-changing-the-font-weight

I'd be happy to fix this quickly if this is something we agree on.

**Comment by danoc** [comment]
That sounds good to me! Feel free to send a PR if you'd like.

**Comment by danoc** [comment]
Fixed in #215
