### ISSUE TITLE
Fix snapshot CSS vendor prefix errors

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#212]
We had an issue where `yarn test` was throwing snapshot errors that turned out to be a result of an old version of node. We should include minimum version requirements so publishers don't get confused.

**Comment by danoc** [comment]
@mateo42 — Do you remember what version of node was causing the issues? Also, do you know if the snapshot issue was related to autoprefixer by any chance?

**Comment by tomgenoni** [comment]
It was an autoprefixer snapshot. A bunch of WebKit prefixes were being removed.

**Comment by danoc** [comment]
And the fix was definitely related to the switching the node version? Or did you all do other things (like `rm -rf node_modules`?)

**Comment by mateo42** [comment]
This issue happened on node v11.13.0 - nvm failed to start in an IDE-based terminal so this was not the expected version.  Things worked as expected after switching back to node v8.11.1.  I ran yarn under 11.13.10 and again after switching back to 8.11.1 so some dependencies may have changed, but I didn't check which ones.

**Comment by danoc** [comment]
Ok, cool. That's helpful for debugging.

**Comment by danoc** [comment]
Was able to reproduce this with `yarn test`.

1. Got CSS vendor prefix snapshot errors with `yarn test`.
2. Tried `yarn install --force && yarn test` but no luck.
3. Ran `yarn run build:dist && yarn test` and then it worked.

`yarn run build:dist` deletes [the cache](https://github.com/thumbtack/thumbprint/blob/master/scripts/should-build-package.js) and forces all of the packages to re-build.

To fix this, we should either:

1. Improve the cache to take changes to `node_modules` into account.
2. Remove the cache
3. Kill the cache before running tests.

To decide, we need to first measure the impact of removing the cache functionality. The cache was built back when we had 50+ packages and saved us about 10 seconds on each documentation build and test run. It may be less of an impact now that we have fewer packages.

**Comment by danoc** [comment]
For posterity, here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/916038/56700443-20604200-66af-11e9-89b4-f64fc5e49b25.png)
