### ISSUE TITLE
Implement Avatar toolkit

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#25]
## 🎨 Designs
https://www.figma.com/file/YrpLNWoOwvEADbyFBWzuKv0V/Thumbprint-Global?node-id=2%3A0

### Renames and deprecations

- [x] [Breaking] Change default `Avatar` export to be a named `UserAvatar` export. The package will ultimately export two components: `UserAvatar` and `EntityAvatar`.
- [x] Indicate that avatar badges (`hasUnreadNotifications`, `isChecked`, and `isOnline`) are deprecated.

### Color changes

These two can be done together and, IMO, can be released as a minor version bump.

- [x] Change the [style of the initials](https://www.figma.com/file/ILP0YIrg8YsGJLeQChrZpsRi/Thumbprint-Web?node-id=24%3A4) when no image is provided.
- [x] [Change "Blank Avatar Colors"](https://www.figma.com/file/ILP0YIrg8YsGJLeQChrZpsRi/Thumbprint-Web?node-id=24%3A4) to match design.

### Size changes

- [x] [Breaking] Change extra-large size to `140px` (currently `124px`).
- [x] [Breaking] Rename `large` to `medium` (remains `72px`), `medium` to `small`, and `small` to `xsmall`.
- [x] Add a new large size that is `104px`.

### Other potential tasks

- [x] We use object-fit to center align the image. How can we do this in a way that works in IE 11 and doesn't sacrifice lazy-loading or accessibility? (#1328)
- [x] Can we use this with the image service?

**Comment by danoc** [comment]
Example of how to deprecate part of a MDX file:
https://thumbprint.design/components/grid/scss/

**Comment by danoc** [comment]
For posterity, here are the size changes:

https://docs.google.com/spreadsheets/d/1lR050vi_6SHNae5hSQ73hsHrx6xJa6B_Yzxw2EGUvoQ/edit?usp=sharing

**Comment by lavelle** [comment]
Remaining tasks in order

- [ ] Update codemod to rewrite `EntityAvatar`
- [ ] Merge size changes to both components
- [ ] Remove `hasUnreadNotifications`
- [ ] Add backdoor prop to allow custom dimensions
- [ ] Release a new version with all the breaking changes
- [ ] Bump package version in website, and run codemod. For all `xlarge` instances, use the backdoor prop to change immediately without design approval

Then to follow up 

- [ ] Rename all instances of `Avatar` in website to `UserAvatar`
- [ ] Remove `Avatar` alias and publish another breaking change
- [ ] Bump package in website again to prevent anyone else using `Avatar` in future

Finally, in the future

- [ ] Add `isOnline` prop to `EntityAvatar too
- [ ] Deprecate the `isChecked` prop

Whew!

cc @danoc @bgando to keep track

**Comment by lavelle** [comment]
Let's make a new ticket for actually deleting the `isChecked` prop some time in the future. Everything else here is done so we can close it out.
