### ISSUE TITLE
Create Pill component in React

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#251]
## Design:

https://www.figma.com/file/YrpLNWoOwvEADbyFBWzuKv0V/Thumbprint-Global?node-id=396%3A160&viewport=81%2C49%2C0.6646246314048767

_(Only accessible to Thumbtack employees.)_

## Notes

* The consumer doesn't pass in literal color values. There will be a property called `color` (not `theme`) that they can control. `color` will be accept strings like `blue`, `green`, `indigo`. The component itself will interpret this and choose the correct background, text, and icon colors.
* The icon property can be called "icon" since icon only appears on left. It doesn't need to be `iconLeft` since we don't expect there would be a `iconRight`.
* Developers should use `tiny` sized icons.
* The border (corner) radius is 6px. If the user increases the font size and the pill becomes taller, the border radius should remain at 6px.
* The text in the pill should never wrap

**Comment by tomgenoni** [comment]
One correction.  Since the height is `24px` the border radius on each corner should be half that:`12px` instead of `6px`.

**Comment by tomgenoni** [comment]
Merged in https://github.com/thumbtack/thumbprint/pull/254
