### ISSUE TITLE
[@thumbtack/thumbprint-react]: Custom alignment for <Checkbox> and <Radio>

### ISSUE THREAD

**Issue by jichan-thumbtack** [thumbtack/thumbprint#266]
In `<Checkbox>` and `<Radio>` components, the root containing input and text (label) are always vertically center-aligned.
(i.e. https://github.com/thumbtack/thumbprint/blob/master/packages/thumbprint-react/components/Checkbox/index.module.scss#L6)

I've seen several designs where we would want them to be aligned at the start, especially in case where text wraps over multiple lines. Previously, I got around this by having two separate `<Checkbox>` component and vanilla `<label>` tag but seeing that this is a recurring pattern, what do you think about adding `align` prop to`<Checkbox>`/`<Radio> `components whose value may be either 'center' or 'start' (open to naming suggestions). I can put up a PR if this is okay. 

![screenshot-www figma com-2019 06 03-17-50-16](https://user-images.githubusercontent.com/40370813/58843872-4de2c880-8629-11e9-905c-9e589667f57a.png)
![screenshot-www figma com-2019 06 03-18-00-09](https://user-images.githubusercontent.com/40370813/58843902-77035900-8629-11e9-8351-e27a4ca38e34.png)

**Comment by danoc** [comment]
Thanks for the thoughtful issue, @jichan-thumbtack!

One issue I see in the first screenshot is that the spacing between the checkbox and the text is not standard. Would that be an issue?

Regardless, I'm open to adding a prop for the vertical alignment. Seems like a common pattern! What do you think it should be called? `verticalAlign`? `checkboxVerticalAlignment`? Would it be `propTypes.oneOf('top', 'center')`?

**Comment by jichan-thumbtack** [comment]
I talked with designer and he was fine with using the standard Checkbox's horizontal spacing. However, I realize the bigger problem is with vertical spacing. I feel like the top/bottom margin around the input should also be configurable such that it aligns nicely with line-height of the first line of label (since Checkbox's children (=label) can be an any node of arbitrary line height)

![screenshot-localhost-9001-2019 06 04-11-50-51](https://user-images.githubusercontent.com/40370813/58905676-28a09980-86bf-11e9-8cba-5ac1c42a1b70.png)

I don't want to bastardize the interface any further but what do you think of one extra prop (such as `checkboxMargin`) that accepts a similar string as `props.labelPadding`? (I would still want to use `<Checkbox>` and all its supported functionality instead of having to customize a vanilla <label> tag just for this issue in a relatively common scenario)

I like `checkboxVerticalAlign` `checkboxMargin` for prop names, and I agree we can limit it to just propTypes.oneOf('top', 'center').

**Comment by tomgenoni** [comment]
@jichan-thumbtack I agree the vertical alignment is off but I think we could avoid adding the `checkboxMargin` prop and fix it in CSS. For `checkboxVerticalAlign="top"` try `margin-top: 2px`. In my testing that works for the possible range of font-sizes/line-heights we support.

**Comment by danoc** [comment]
+1 on Tom's recommendation. I imagine that there is a `margin-top` value that we can pair with `checkboxVerticalAlign` that looks good in all cases.

**Comment by jichan-thumbtack** [comment]
Thanks for the suggestion. Assuming the provided label is a standard `<Text size={1,2,3} />` components, this is what looks like with `margin-top: 2px`. Not pixel-perfect, but I think it can work especially given that default `size={1}` are most commonly used. I can go ahead and submit PR if you guys can confirm.

![screenshot-localhost-9001-2019 06 04-13-29-03](https://user-images.githubusercontent.com/40370813/58911493-c2bb0e80-86cc-11e9-955c-3487a67b8ccc.png)

**Comment by danoc** [comment]
Looks great to me! Feel free to make the PR!

**Comment by tomgenoni** [comment]
Could also try 1px, that might be the happy medium.
