### ISSUE TITLE
[tp-ui-react-grid]: Add example for single column layout

### ISSUE THREAD

**Issue by dcapo** [thumbtack/thumbprint#28]
Chatted with Dan about this offline. The React Grid has been simplified and doesn't support a common use case where a single Column of content should be centered in the grid. The recommendation is to use Atomic width and margin classes instead of a Grid.

**Comment by tomgenoni** [comment]
https://github.com/thumbtack/thumbprint/pull/142 adds an example to the docs that will auto close this ticket. @webbower if you feel strongly we should have a component let's open a ticket to track that request specifically.

**Comment by danoc** [comment]
I'd vote for waiting a few weeks to see if the documentation clarifies this before we make a component for it.

(This is probably one of our most frequently asked questions.)
