### ISSUE TITLE
Enable eslint-plugin-lodash to catch some browser API bugs at build time

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#293]
We enabled `eslint-plugin-compat` to catch uses of browser methods that are not available in old but supported browsers like IE11. However, this has some false negatives – it does not catch prototype methods like `Array.find` and `String.startsWith`.

`eslint-plugin-lodash` can catch these, although it can also flag some false positives for other methods with those names – eg. a custom class `X` with its own `find` method would be flagged due to the limitations of static analysis of untyped code.

I propose we enable this plugin with a conservative configuration:

- All the "error" lint rules – these are uncontroversial
- None of the "stylistic" ones – these don't catch browser bugs, and can cause arguments about preferred style
- Enforce the import syntax to only allow `import method from 'lodash/method';` type imports, and ban `import _ from 'lodash'` which will give you the monolithic build and massively bloat our bundles.
- Enable the `prefer-lodash-method` rule, but *only* for methods that are not supported in IE11. Others, like `Array.map` which are available everywhere can still be used. Here is my list of methods I know to be unsupported in IE11. Please update the issue if you find more:
   - ` _.find`
    - `_.includes`
    - `_.startsWith`
    - `_.values`
    - `_.entries`

All of these rules would only be enabled for the `thumbprint-react` package – any other code in the repo that is not distributed to browsers can use whatever it likes since it only runs in Node.

cc @danoc let me know if you agree with all that.

**Comment by danoc** [comment]
@lavelle — This all sounds good to me!
