### ISSUE TITLE
Convert code to TypeScript

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#294]
This would be a big project, but I believe it would be worth the effort. 

Some of the benefits:

- Automatic API documentation generation
- Much simpler and cleaner code than `propTypes` and `defaultProps`, and stronger checks that happen at build-time instead of run-time
- In-editor autocomplete for method names and arguments for people consuming Thumbprint (this is HUGE, IMO, and would make it worth it even if nothing else was true
- Much safer and easier refactors when shipping breaking changes, as any incorrect uses of the API could be caught by the tooling at build time (even in plain JS codebases like Website, as long as they had the TS type-checker installed as a dependency)

**Comment by lavelle** [comment]
cc @danoc LMK what you think

**Comment by danoc** [comment]
I agree with all the benefits, but two concerns are:

1. Is it worth ramping up on this at the expense of other work (Thumbprint Native, for example)?
2. This makes it harder for non-Thumbprint engineers to contribute. Is that worth it?

My initial answers to those are:

1. Probably not worth the trade-off.
2. Probably not an issue. I think our front-end engineers enjoy that they usually learn a new thing or two when contributing to Thumbprint.

**Comment by toraora** [comment]
+1 on eventually using Typescript, though not necessarily in the near future. 

It can be incrementally adopted, but then you end up in a weird half-state where new code is being written both ways, which is probably bad.

**Comment by danoc** [comment]
I'm going to close this for now, but let's re-open it if something changes and we think this becomes worthwhile in the near future.

**Comment by lavelle** [comment]
One thing I didn't previously consider is that you can create external [typescript definition files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) which document the API of your library without actually modifying the JS code itself. This would be a significantly simpler effort than actually rewriting our components, and would provide the single biggest benefit, namely auto-completing method and component APIs inside website when consuming the library.

I think we should consider doing this soon. The work can be done in very small increments, maybe starting with a single component and working from there.

**Comment by lavelle** [comment]
Assigning to myself – i'm going to experiment with this

**Comment by danoc** [comment]
I don't think we should tackle this until we have a stronger component library on native. And if we were to tackle it, it should go through the larger RFC process and be brought up at a front-end meeting.

**Comment by lavelle** [comment]
I guess I point above is it doesn't have to be either or. It only takes a few minutes to write definitions for a component – it's the type of work you can do when you have some downtime between other tasks. Afaik I'm not going to be working on Native so me working on this wouldn't take away from native efforts.

Happy to discuss in the frontend meeting, but adding these type definition files is strictly an enhancement, doesn't require modifying any component code directly, and will be invisible to consumers unless they choose to use them. 

Given how lightweight and unintrusive it is, I think it makes sense to add them as we go.

**Comment by lavelle** [comment]
cc @dcapo
