### ISSUE TITLE
Find a way for Gatsby to preserve scroll position on hot module reloading

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#327]

**Comment by danoc** [comment]
Are there any console errors from `react-hot-loader` when the page does reload? You may need to check "Preserve log" to see them.

**Comment by lavelle** [comment]
Seems like there's some active work on this, with issues being updated in the last few days.

We should probably wait to hear news on those

https://github.com/gatsbyjs/gatsby/issues/12560
https://github.com/gatsbyjs/gatsby/issues/12997

**Comment by danoc** [comment]
![Kapture 2020-01-07 at 16 04 26](https://user-images.githubusercontent.com/916038/71939530-dc8f6900-3167-11ea-9bf2-2edf5d893e13.gif)

I think this has been fixed. Will close.
