### ISSUE TITLE
Search bar redirects to production even on development

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#338]

**Comment by danoc** [comment]
@lavelle — Can you a take a look at the Agolia DocSearch docs and see if there's a way to change it for development?

**Comment by lavelle** [comment]
Couldn't find anything in the docs but I left an issue here https://github.com/algolia/docsearch/issues/732

**Comment by danoc** [comment]
Sweet! Seems like it's possible. https://github.com/algolia/docsearch/issues/732#issuecomment-504648111
