### ISSUE TITLE
Remove backticks from test names across the codebase

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#358]
Few reasons:

- Makes it harder to Cmd+f for the test name to jump to the failing test after seeing it in the terminal
- Breaks terminal commands that include the test name. For example running

  ```
  yarn test:jest test.jsx --testNamePattern "`mouseleave` closes the tooltip 
  immediately if closeDelayLength is 0"
  ```

  gives the error `zsh: command not found: mouseleave`.

- If you want to interpolate anything into the string using a backtick-quoted string, you then have to go through and escape all the backticks.

In general, I find test names are better when they're plain english, and any code names are left to the contents of the test itself.

**Comment by danoc** [comment]
Going to close this one as a "won't fix" since we haven't gotten this feedback from others and I personally prefer the backticks for legibility.
