### ISSUE TITLE
Improve PropTypes docs for `instanceOf` and `arrayOf`

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#378]
For the DatePicker, we see this:

![image](https://user-images.githubusercontent.com/550185/61334586-68d75980-a7df-11e9-88da-64bc2901d3f0.png)

But I would rather see something like

> This prop has 3 types:
> - `string`
> - `Date`
> - `array` of `string`s or `Date`s

So there are a couple of tasks here

- [x] Make it detect what the actual type is for `instanceOf` ones
- [ ] Make it show what the array is of for `arrayOf` ones

**Comment by volanStudio** [comment]
There are no `instanceOf` props types in any of the current components :). Might be worth putting this in the cooler (as it is a good idea) or even deleting as "will not fix".

**Comment by lavelle** [comment]
Now we've migrated to TypeScript, this is obsolete. We should instead  focus on #572, and improve how we display TS API definitions to readers of the docs.
