### ISSUE TITLE
Create `thumbprint-scss` and `thumbprint-global-css` package

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#38]
Following the recent consolidation of our React components into a single package, we're planning the same for our SCSS components. This has a few advantages:

- Simplifies dependencies in React and SCSS files
- Enables distribution of Thumbprint CSS files for non-React work
- Simplifies change, release, and update process—freeing up time to for Design Systems to build components.

Notes: 
- This work does not introduce any breaking changes. These are all code consolidations and swaps. No code will be removed.
- The `font-face` package will remain separate.
- The names/paths of packages may change slightly.

## New packages
We're creating the following 2 packages:

- [x] **`thumbprint-global-css`**:  Distributes:
1. `thumbprint-global.css`   Contains global styling for our reset, body, and default anchor styles. 

- [x] **`thumbprint-scss`**: Distributes:
1.  `thumbprint-mixin.scss`  Contains only mixins and our lone (deprecated) function. 
2.  `thumbprint-components.css`  Contains the output of all SCSS components — e.g., buttons, type, form elements. 

### Related tasks

- [x] Update documentation to work with the new file structure. (https://github.com/thumbtack/thumbprint/issues/37)
- [x] Update documentation to explain how to include CSS and SCSS dependencies.

**Comment by danoc** [comment]
@tomgenoni — I think we can close this one.

**Comment by tomgenoni** [comment]
I can move the migration task into another issue so the scope of this one isn't so big.

**Comment by danoc** [comment]
That's probably best off for JIRA/some other tracker since it's website specific.
