### ISSUE TITLE
Consider new rules for Atomic, or better documentation for existing ones

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#387]
Here are the top [1000 CSS rules inside website](https://gist.github.com/lavelle/52c4bfda0ec055b5f3f0ca8089283fe0). Most of them already exist as atomic classes, suggesting we either need an effort to go and rewrite old code, or we need to document the classes better so people know about them

For rules in this list that do not have atomic equivalents, you can go through and see which ones are used most frequently.

cc @danoc @tomgenoni

**Comment by lavelle** [comment]
It looks like everything in the top 100 already has an atomic class, but if you see any with > 10 uses that don't have atomic classes, those would be good candidates to add

**Comment by tomgenoni** [comment]
I'd guess the top ones are from old code. A quick not-entirely-precise search in website turns up 462 instances of the `flex` class. The rule of thumb had been unless we're refactoring a good chunk of component we leave the CSS as is. 

Will look at the others.
