### ISSUE TITLE
Speed up mounting of `Image` component

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#416]
The `Image` component is breaking a test in `website` because it's taking too long to mount. 

We should:

1. Do a small performance audit of it to identify which parts are the slowest when rendering it with `mount` in Enzyme.
2. Depending on the results, speed up the component.

**Comment by toraora** [comment]
if it's network related, can we get away with using base64 images rather than placeholder.com ones?

**Comment by danoc** [comment]
Hi @toraora! My understanding is that the unit tests don't actually make HTTP requests to load images. I think the performance concerns are not related to network calls.

**Comment by danoc** [comment]
I've dug into this and the issue is that `getComputedStyle` gets run many many many times because of scrollparent. I also noticed that `getComputedStyle` runs over 10x slower in Mocha/JSDom than in the browser. Because of that, I'm not sure if is a performance issue beyond our testing environment.

That said, there are ways we can speed up `scrollparent`. These are suggestions from @webbower:

1. `getComputedStyle` is [called 3 times for a single node](https://github.com/olahol/scrollparent.js/blob/5b8186327d1240a1fb339210b9b49135436bea89/scrollparent.js#L23). The result can be reused.
2. `scrollparent` proactively [creates the whole parent hierarchy](https://github.com/olahol/scrollparent.js/blob/5b8186327d1240a1fb339210b9b49135436bea89/scrollparent.js#L35) before iterating through them (rather than lazily crawling and testing).

We could fork `scrollparent` and contribute to the project or [adopt this solution](https://stackoverflow.com/questions/35939886/find-first-scrollable-parent/42543908#42543908) that @webbower found.
