### ISSUE TITLE
Expose `month` prop in DatePicker

### ISSUE THREAD

**Issue by jichan-thumbtack** [thumbtack/thumbprint#418]
The currently displayed month in `DatePicker` is uncontrolled, so it's hard for the consumer to trigger a change in `DatePicker` to display a particular month (use case: user currently sees September but clicks "Today" button and we wish to display "August" in date picker); changing selectedDate doesn't change the internal state of what month is being shown. 

`react-day-picker` seems to have `month` prop (https://react-day-picker.js.org/api/DayPicker#month; in addition to `initialMonth` we are using) that makes the current month being shown fully controlled. Is it okay if thumbprint `DatePicker` also pass through `month` prop to the underlying `react-day-picker`?

**Comment by danoc** [comment]
Thanks for this issue, @jichan-thumbtack! 

@lavelle — What do you think is the best approach here? We already use `react-day-picker`'s `initialMonth` prop and expose a `onMonthChange` prop. Go fully controlled? Support both? Something else?

**Comment by lavelle** [comment]
Yeah for consistency with `value` let's go fully controlled. Means another breaking change, but having these half-controlled components just leads to bugs and confusion.

**Comment by danoc** [comment]
@lavelle — Cool, that sounds good. Would you like to take this one? 

@jichan-thumbtack — What do you think of the approach?

**Comment by jichan-thumbtack** [comment]
Yes, that sounds good! Let me know if I can do anything to help
