### ISSUE TITLE
Image component: add prop to specify sizes and bypass lazyloading

### ISSUE THREAD

**Issue by mateo42** [thumbtack/thumbprint#426]
We could use a prop that allows us to specify the sizes attribute manually for server rendering.  This would also bypass lazy loading as it would force the picture tag to render with sources on the server.

Use case: landing pages have above the fold hero images which cannot render until the client JS has executed.  This causes some performance metrics like Speed Index to regress due to the delay before the image is loaded.

Example:
<Image ... forceRenderWithSizes="100%">

**Comment by tomgenoni** [comment]
I don't have an objection to adding this, though I would want to have a separate prop for disabling lazyloading. I think that would be clearer given how complicated this component already is. 

But before we do that do we have other metrics, like engagement or click throughs, that went down? I understand how it could affect the Speed Index but in this case the image is decoration, it has a placeholder (of sorts) and doesn't affect layout.

**Comment by mateo42** [comment]
That's a good point - Dan and I discussed this yesterday, but after giving it some more thought I think it makes sense to have two props:

- forceSizes: string (undefined) - skips container size calculation (image may still be lazyloaded)
- enableLazyLoading: bool (true) - if false component immediately renders picture component

If you want to SSR and have enableLazyLoading={false} then the component needs to be aware that it might be running in a context where it can't calculate the container size and may render nothing.

Initially I was thinking forceRenderWithSizes would be a more purpose oriented way to name the API, and we could always choose to keep that in our internal wrapper.

**Comment by tomgenoni** [comment]
How about `disableLazyLoading` (defaults false) since, like the `disabled` attribute, it negates the default behavior?

**Comment by mateo42** [comment]
Makes sense.
