### ISSUE TITLE
[@thumbtack/thumbprint-react] Add ability to constrain `<ModalDefault>` height

### ISSUE THREAD

**Issue by jichan-thumbtack** [thumbtack/thumbprint#433]
In some modal flows, I'm finding the need to constrain the modal height on desktop so that it's consistent even across modal content (whose length varies) changes.
(https://www.figma.com/file/IcbYHDSlj6A1gXJTpvM1UQF5/%F0%9F%97%93-Calendar-%2B-Availability?node-id=4188%3A1097)
I've found this to be a relatively common use case (i.e. it's a bit jarring when the modal height suddenly expands/constrains as we switch from loading state or when some collapsed content within modal gets revealed, etc.)

Currently, there doesn't seem to be a good way for consumer to apply a fixed height to modal. 
It's possible to render a child of `<ModalDefault>` as `<div>` with some fixed height, but it's deficient because
(1) We'd want the entire modal (i.e. including sticky footer and close button row) height to be consistent, not just the children
(2) When children are long, this wrapper `<div>` overflows; however, there already is a container that actually controls the overflow (`<div className="index-module__contents">`) and leads to weird styling issues (i.e. overflowing children will bleed into the bottom padding of `<div className="index-module__contents">`)

I also attempted using `<ModalDefaultAnimatedWrapper>` but `<ModalFooter isSticky>` throws a ref error (`TypeError: Cannot read property 'current' of null`) and it's just a lot of reinventing `<ModalDefault>` mechanics when the only thing I want more is height constraint. 

I would prefer if `<ModalDefault>` can accept an additional `height` prop (like `width`) that simply constrains height of the entire modal (whether it's pixel, percentage, or discrete values) and I would be happy to contribute to the change. What are your thoughts?

**Comment by tomgenoni** [comment]
@jichan-thumbtack Are you not able to constrain the height of the content inside of the modal? Eg. (excuse the pseudo code):

```
<Modal>
  <ModalDefaultContent>
     <my-content-wrap height="500px">
        <my-content>i'm the content that has overflow, flexes</my-content>
        <my-footer>button, no flex</my-footer>
     </my-content-wrap>
  </ModalDefaultContent>
<Modal>
```

**Comment by jichan-thumbtack** [comment]
Yeah those issues are not present with the particular example, but
(1) is a problem when you use `<ModalDefaultFooter isSticky>`. When the footer is sticky, it is placed outside of the `contents` node. 
(2) is a problem when contents are longer than the specified height. If I apply overflow to `<div>` with `height: 300px;`, then we would have double scrollbars. If we let it overflow that `<div>`, it bleeds into padding of the `contents` node. 
![screenshot-thumbprint design-2019 08 22-15-34-41](https://user-images.githubusercontent.com/40370813/63554474-64931000-c4f2-11e9-8386-603dcfd1a34b.png)

The above example essentially renders: 
```
<div className="flex flex-column"> // modal container node
     <div style="overflow: scroll-y; padding: 20px;"> // modal contents node
           <div style="height: 300px;">Content overflows beyond the immediate wrapper</div>
     </div>
    // modal sticky footer and close button
</div>
```
I'd think applying height to the root container seems like it would result in the most predictable layout, but I'm open to suggestions

**Comment by tomgenoni** [comment]
@danoc I talked with @jichan-thumbtack and it looks being able to add a fixed `height` to https://github.com/thumbtack/thumbprint/blob/master/packages/thumbprint-react/components/ModalDefault/index.jsx#L389 would produce the behavior needed. 

It may be possible to get the effect without it but it involves rebuilding the layout structures that already exist. We like to discuss with you since you have better context on this component.

**Comment by danoc** [comment]
Ok, sweet! Thanks for digging into it. Would chatting on Monday work?

**Comment by danoc** [comment]
This was done in #444.
