### ISSUE TITLE
[@thumbtack/thumbprint-atomic] Reconsider negative margin classes

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#435]
The `-ma#` classes seem unused and could likely be removed. Also look into adding `-mh#` classes instead.

**Comment by danoc** [comment]
@tomgenoni It's still unused in `website` (regex: `-ma\d`). Want to remove?

**Comment by tomgenoni** [comment]
Yeah, if they haven't been used yet prob good to remove. I'll make a task to do this.
