### ISSUE TITLE
Error: Plugin gatsby-transformer-thumbprint-atomic requires a package.json file

### ISSUE THREAD

**Issue by sid995** [thumbtack/thumbprint#451]
Getting error that states package.json file required for gatsby-transformer-thumbprint-atomic, even after installing all the required packages. Help needed.

**Comment by danoc** [comment]
Hi Siddharth, please check that you're on a supported version of Node and Yarn:

https://github.com/thumbtack/thumbprint/blob/master/CONTRIBUTING.md#developing-thumbprint-locally

I'm going to close this, but feel free to comment if you have further questions.

Thanks!
