### ISSUE TITLE
Coda is sometimes failing the Netlify build

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#474]
It is failing with this error:

```
FetchError: invalid json response body at https://coda.io/apis/v1beta1/docs/bXyUQb2tJW/tables/Implementations/rows?useColumnNames=true reason: Unexpected token < in JSON at position 0
```

We should try to better understand what the error is. Perhaps wrap it in a `try/catch` and add some debugging information so we can reproduce it.

**Comment by danoc** [comment]
@lavelle and @tomgenoni  — LMK if you see this happen again.

**Comment by danoc** [comment]
@lavelle — Have you seen this happen recently? If not, let's close the issue and re-open if it comes back.

**Comment by lavelle** [comment]
No, not since the first time
