### ISSUE TITLE
[@thumbtack/thumbprint-atomic]: Box shadows in IE 11 are too faint

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#476]
### Issue
The Atomic classes for box shadows, e.g., `shadow-300`, render considerably fainter in IE 11. 

### Suggested Fix
Apply CSS to IE 11 only that applies `outline: 1px solid $tp-color__gray-300;`. 

`border` behaves similarly and looks good because it follow the contours of the border radius, but a `border` also changes the dimensions of the box, decreasing the internal width by 2px (1px on each side), and in some rare cases that could lead to visual inconsistencies. The height is also increased if it's not constrained. 

#### IE 11 Screenshot 
![Screen Shot 2019-09-27 at 3 10 01 PM](https://user-images.githubusercontent.com/1171072/65805012-e9e49280-e138-11e9-8170-5f25bac802ca.png)

cc @xanderwebs

**Comment by xanderwebs** [comment]
Outline looks good to me as long as there aren't going to be accessibility concerns and whatnot for using outlines.

**Comment by webbower** [comment]
Are you combining `box-shadow` + `outline`/`border` in these cases? If so, maybe give them 50% opacity since the top and left lines looks pretty heavy compared to the shadowy sides. IE11 does support `rgba()` https://caniuse.com/#search=rgba

**Comment by danoc** [comment]
@tomgenoni — This would be a good fix-it week task if you want to continue working on it.
