### ISSUE TITLE
Add ref support on input components

### ISSUE THREAD

**Issue by mateo42** [thumbtack/thumbprint#492]
For input components it could be useful to developers who want to programmatically focus or invoke events on those inputs to have access to the DOM ref.  To do this, I think Thumbprint components should use React.forwardRef to wrap the existing components and pass the forwarded ref to the internal input element.

This would need to be considered a major version change: https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers

For that reason, I don't think this is a high priority issue.

A challenge in implementing this is keeping the components as class components while being able to wrap them.  To wrap a class component you must pass the ref as a prop to the inner component.  This prop is not part of the public API for the component, so it means writing a second internal component to handle the ref.

Alternatively, we could convert the class components to functional components (some may need to use hooks to accomplish this).  I had some success trying this out on the Input component, but it ran into a snag trying to test the focusing behavior as you can't spy on the internals of the functional component.

An example of a forwardRef component: 
`const Input = React.forwardRef((props, ref) => { /* ... */ return <Input ... ref={ref} /> });`

**Comment by danoc** [comment]
Thanks for the thoughtful issue, Matt!

Here's some previous discussion on this:
https://github.com/thumbtack/thumbprint/issues/112

And also:
https://github.com/thumbtack/thumbprint-archive/pull/1339 (Internal to Thumbtack employees)

I'm open to doing it. @lavelle, do you want to take this on?
