### ISSUE TITLE
Convert Alert component to React

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#500]
The task is to convert this component into React:

https://thumbprint.design/components/alert/scss/

**Comment by danoc** [comment]
After we do this, we should clean up the work in Gerrit CR 125235 (internal to Thumbtack).

**Comment by danoc** [comment]
@volanStudio — Could you take this one on? Take a look at the `CONTRIBUTING.md` file for tips on getting started.

**Comment by lavelle** [comment]
This is done in #521
