### ISSUE TITLE
Code samples are difficult to read becaue of poor contrast

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#525]
<img width="897" alt="Code that is difficult to read" src="https://user-images.githubusercontent.com/916038/67345203-0df48300-f4ef-11e9-84de-ea6c6ed7b744.png">

***

**Example:** 
https://thumbprint.design/guide/product/breakpoints/

**This is the relevant file:**
https://github.com/thumbtack/thumbprint/blob/master/www/src/components/mdx/code-block/prism-theme.js

That file is used by both the React (powered by react-live) and non-React code components:

* `www/src/components/mdx/code-block/index.jsx`
* `www/src/components/mdx/code-block/react-code-block.jsx`

That theme file is in a syntax that works with `prism-react-renderer`:

https://github.com/FormidableLabs/prism-react-renderer

**Comment by danoc** [comment]
@volanStudio or @tomgenoni — Do either of you want to take a stab at this?

**Comment by danoc** [comment]
I don't have a particular theme in mind here. I think either tweaking the current one or replacing with something that looks better would work well.

**Comment by tomgenoni** [comment]
Happy to pick this up.
