### ISSUE TITLE
Sort required props first

### ISSUE THREAD

**Issue by lavelle** [thumbtack/thumbprint#534]
The required props are usually the most important ones to know about for a component, but right now they can be way down the list. We should probably sort the list in the API docs to show these first. We could also show deprecated props last, or even have them hidden behind a "show more" link

cc @danoc what do you think? I can take this on.

**Comment by danoc** [comment]
Hm, I don't have a strong opinion. Let's open it up to the front-end engineers for feedback? I'll ask on Slack.

**Comment by lavelle** [comment]
it's a minor tweak, just one that popped into my head a few times, and i like to track stuff here instead of just forgetting about it. obviously not high priority.

**Comment by danoc** [comment]
These small tweaks can sometimes have a large impact!

**Comment by danoc** [comment]
Posted in #thumbprint-questions on Slack.
