### ISSUE TITLE
Remove SCSS `form.scss` classes

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#559]
Just realized that this page doesn't appear in the component sidebar and also has an incorrect title and description: https://thumbprint.design/components/form/scss/

It likely broke when we made the move to MDX a while back.

Regardless, this seems like a good candidate for removal as part of The Great Alignment work (#558):

https://github.com/thumbtack/thumbprint/blob/master/packages/thumbprint-scss/scss/form.scss

@tomgenoni — Thoughts? We'd probably need to move the placeholder styles to some other file.

**Comment by danoc** [comment]
* `tp-input-wrap` is used in 7 files (4 are an internal tool)
* `tp-form-fields` is used in 10 files.
* `tp-form-field__item` is used in 12 files.

The latter 2 classes can likely be find and replaces w/ Atomic. We may want to replace the input wraps with [a similar React component](https://thumbprint.design/components/input-row/react/) or Atomic depending on the instance.

**Comment by tomgenoni** [comment]
Yeah, moving it out seems like the right call. Let me know if you want any help with this.
