### ISSUE TITLE
StarRating can display incorrectly as a flex child with siblings

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#571]
Notice that the `StarRating` in this CodeSandbox has `rating={3}` but it gets displayed as `rating={2}` or `rating={5}`. Thanks @toraora and @aislematt for the bug report:

https://codesandbox.io/s/thumbprint-571-ixmdi

cc: @tomgenoni

**Comment by tomgenoni** [comment]
The `StarRating` component is set to `display: inline-block` and the rating functionality relies on the width of the component (~150px). The width of the highlighted stars is expressed in a width percentage, e.g. 2.5 stars becomes `width="50%"` or roughly 75px. 

When this component is an immediate child of a `flex flex-column` parent the width of the star rating becomes 100%. This means that a width of 50% is now computed based on the outer container.

```
<div class="flex flex-column">
   <StarRating.../>
    <div>...other content...</div>
</div>
```

I don't see a good fix in the component itself* so I'd recommend we show an example in the documentation to work around it.

1. Add example with the `<StarRating/>` in a `<div>`.

```
<div class="flex flex-column">
    <div><StarRating.../></div>
    <div>...other content...</div>
</div>
```

2. Add example with an additional `items-start` class.

```
<div class="flex flex-column items-start">
    <StarRating.../>
    <div>...other content...</div>
</div>
```

I'd recommend (1) as it likely has the fewest number of potential side-effects. 

* Note we could add this wrapping `div` to the component but it already has a lot of nodes and is only needed for this one situation AFAIK.

**Comment by danoc** [comment]
Chatted with Tom offline and we decided to simplify the `StarRating` component works so that it doesn't rely on the `width` or `display` of the parent. This will also simplify the outputted DOM which should help avoid the "excessive DOM" warnings in Ligthhouse.
