### ISSUE TITLE
Checkbox HTML includes value attribute even if prop is undefined

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#589]
React adds a `value` attribute (`value=""`) to `input[type="checkbox"]` even if the `value` prop is `undefined`. This prevents the default browser behavior of `value="on"` when the `value` attribute is omitted and causes unexpected bugs if a server endpoint checks for a the checkbox value rather than existence of the checkbox in the form data.

This upstream issue describes this in more detail: https://github.com/facebook/react/issues/17590

Thumbtack employees can also look at IE-545 in JIRA for more context.

**Comment by Amagon96** [comment]
Hi! Seems simple, can I work on this?

**Comment by danoc** [comment]
Hi @Amagon96, thanks for reaching out but we already have a PR for it (#590).

**Comment by Amagon96** [comment]
@danoc I see, thanks man
