### ISSUE TITLE
[@thumbtack/tp-ui-core-mixin]: Reconsider current values

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#6]
## Issue

Currently the `small` and `large` breakpoints used in our media query mixins are outputting confusing numbers : 

- `$tp-breakpoint__small` outputs `min-width: 481px` & `max-width: 482px`
- `$tp-breakpoint__large` outputs `min-width: 1025` & `max-width: 1026px`

when the expected values should probably be:

- `$tp-breakpoint__small` outputs `min-width: 480px` & `max-width: 481px`
- `$tp-breakpoint__large` outputs `min-width: 1024` & `max-width: 1025px`

This happens because the `min-width` value is incremented by `1` to avoid overlap. 

## Fix

- Change `$tp-breakpoint__small` to `480` 
- Change `$tp-breakpoint__large` to `1024` 

This is a breaking change but with no anticipated changes needed by consumers. We should check for any hardcoded instances of breakpoints.

**Comment by tomgenoni** [comment]
Will revisit this once https://github.com/thumbtack/thumbprint/issues/38 is complete.

**Comment by danoc** [comment]
@tomgenoni — Do you still think this is worth doing?

**Comment by tomgenoni** [comment]
No. Don't think trade off is worth it. You can close if you agree.

**Comment by danoc** [comment]
Yeah, I agree. Let's close.
