### ISSUE TITLE
Add three sizes to `Title` component

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#70]
### Problem

There are two problems:

1. We sometimes want `16px` bold text to render as an `h1`-`h6`. While possible with the `Text` component (use `className` and `elementName`), we've received feedback that this isn't ideal.
2. The terminology in [React](https://thumbprint.design/components/type/react/#section-title) and [Figma](https://user-images.githubusercontent.com/916038/51948305-d97aed00-23dc-11e9-805b-25ce9c7d46fd.png) don't match.

### Current state

* The `Title` component [currently supports five sizes](https://thumbprint.design/components/type/react/#section-title) ranging from `40px` to `18px`. All of these are bold.
* The `Text` component can render three sizes: `16px`, `14px`, and `12px`. None of these are bold by default, but the `className` prop makes it possible to make them bold.
* When designers are using the type styles, they're not often thinking about the semantics of `h1`-`h6`.

### Proposal

Add three sizes to `<Title />`. The result would be:

*  `<Title size={6} />`: `16px`, bold, block-level element
*  `<Title size={7} />`: `14px`, bold, block-level element
*  `<Title size={8} />`: `12px`, bold, block-level element

This would be helpful because:

* Developers that want bold `16px` text would no longer need `className="b"`.
* It encourages semantic HTML since `Title` components have the `headingLevel` prop. (In `Text`, you'd need to use the `elementName` prop.)
* It allows us to align the terminology in Figma and React. Figma would have 8 `Title` styles and 3 `Text` styles. Titles are all bold and Text are all normal (non-bold).

***
Thanks @webbower for the initial idea/proposal.

cc: @tomgenoni @jonpkerwin

**Comment by danoc** [comment]
Forgot to mention that this would be a non-breaking change. We'd simply have to update the documentation and Figma.

**Comment by webbower** [comment]
Assuming the new sizes wouldn't have responsive font size changes since they're small enough to start with?

**Comment by danoc** [comment]
Correct, only `Title` sizes `1`, `2`, and `3` will be responsive.
