### ISSUE TITLE
Remove need for reset by baking the CSS into packages

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#84]
This is a proposal to remove the need for a `reset` package in favor of baking the CSS rules into the respective React components and `tp-*` classes.

### How does it work?

We'd move all of the `<button>` code in [`tp-ui-core-reset`](https://github.com/thumbtack/thumbprint/blob/master/packages/tp-ui-core-reset/_index.scss) into the `Button` React and SCSS components. Instead of using the global `button` selector (as the reset does), the components would come with those rules baked in.

### What's wrong with resets?

The reset has a few issues:

* It's a requirement for using our components but it can be scary to set up on an existing codebase since the global reset styles may conflict with other global styles or existing resets.
* It has to be loaded before all of the other code. Relying on source order is dangerous and can make it scary to make changes. This is especially true if importing CSS in a JS file (via webpack) since few developers know how webpack orders the outputted CSS.
* It means that the React and SCSS components technically have a `peerDepedency` on the reset. Yet they don't directly use or import the reset themselves.
* We don't actually know how much of the reset is needed or used. Parts of it can become obsolete as browsers evolve and fix inconsistencies.

### So, no resets needed ever?

Not necessarily. Websites that use Thumbprint could still use a reset or normalize if they'd like. It could be helpful for their custom components. This proposal is about "strengthening" the Thumbprint components so that:

1. They don't have a dependency on a reset.
2. Their styles don't get overridden by a reset, normalize, or other global CSS that exists on a site.

***

### Migration plan:

* [ ] Move reset rules into React components
* [ ] Move reset rules into SCSS components
* [ ] Remove reset from Thumbtack codebases (with a lot of manual QA).

**Comment by bawjensen** [comment]
To be clear, this means that the components styling would work just fine on any browser even without a reset? And not necessarily that we would bake reset-type styling into our components, e.g. we wouldn't have the button component including styling that carries with it a reset to `button` styles?

**Comment by danoc** [comment]
The idea is that the `Button` React component, for example, should work on all browsers even if the reset didn't exist.

Our reset, for example, adds `margin: 0` to all `<button>` elements. Instead of having a reset do that, the `Button` React component's SCSS module would include that rule.

**Comment by tomgenoni** [comment]
I believe the idea is that all the previous reset CSS would be moved into the React SCSS or plain SCSS file behind a class name. So instead of targeting a button element globally:

```
button  {
    font-family: inherit;
    font-size: 100%; 
    margin: 0;
}
```

You'd move that CSS into a Button package and add it to the class:

```
.tp-button  {
    font-family: inherit;
    font-size: 100%; 
    margin: 0;
}
```

We don't mix our CSS with many 3rd party tools but it help would in those situations as well if their reset differed from ours.

**Comment by danoc** [comment]
Going to close this one as a "won't fix" for now. I still think it's a good idea, but we realistically won't be able to prioritize it.
