### ISSUE TITLE
Remove support for loading state in secondary button style

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#87]
The usage rules correctly state that it should only be available to `primary` buttons but our component currently supports the loading indicator in `primary` and `secondary`. 😬

https://github.com/thumbtack/thumbprint/blob/171bd7d8ce1f9b86a190d256addeb39f987d4f54/packages/thumbprint-react/components/UIAction/themed.jsx#L12-L15

**Comment by danoc** [comment]
This is technically a breaking change. We should first check to see if we've ever used the `isLoading` prop on a `secondary` button.

**Comment by benknight** [comment]
The Solution Center is currently using the "caution" theme with isLoading:

![d3ux1w61ta5f1h cloudfront net_solutioncenter_d1 (1)](https://user-images.githubusercontent.com/786691/56198854-eadfa700-6065-11e9-99cf-95e0c308524d.png)
![d3ux1w61ta5f1h cloudfront net_solutioncenter_d1 (2)](https://user-images.githubusercontent.com/786691/56198809-d9969a80-6065-11e9-9a01-896b0a12ea4e.png)

I assume this would be a breaking change in this case.

**Comment by danoc** [comment]
Good call. A few days ago we decided against making this change but I had forgotten to close the issue. Will close it now.

**Comment by mattybow** [comment]
I'm not sure I understand where this landed.  Can we use the blue loader dots for a button with a caution theme?

**Comment by danoc** [comment]
Based on Figma it seems like we should be supporting it:

![image](https://user-images.githubusercontent.com/916038/135467834-e3e25db3-cfd1-4276-8081-2c19bc65c82c.png)

(But I've confirmed that we don't currently support it in code.)

cc: @bgando
