### ISSUE TITLE
Document `thumbprint-global-css` and `thumbprint-scss` packages

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#91]
`thumbprint-scss` will render as they have before along side each React equivalent.

`thumbprint-css` is a new package. Could/should it be documented like Atomic?

**Comment by tomgenoni** [comment]
For now leaving them as separate directories as before and so `README.mdx` will be separate files. Realized this was important. This mimics the `thumbprint-react` organization.

**Comment by tomgenoni** [comment]
Decision is to:

- Add info to each of the package README 
- Add doc to Overview section that explains full tech path: React > Atomic > Tokens > Custom SCSS
- Add page in wiki that explains usage of CSS only Thumbprint packages (font, global, components, atomic)

**Comment by danoc** [comment]
@tomgenoni — I think we can close this one.
