### ISSUE TITLE
<Image> does not support the `style` prop in TypeScript

### ISSUE THREAD

**Issue by dcapo** [thumbtack/thumbprint#940]
There are examples in the [Thumbprint docs for the Image component](https://thumbprint.thumbtack.com/components/image/react/) that use the `style` prop to set the image width.

<img width="870" alt="Image__React____Thumbprint" src="https://github.com/thumbtack/thumbprint/assets/880266/bac2cf46-6a8a-41ed-8056-bb04b5286092">

Currently, a TS error occurs if you try to add such a `style` prop to the `<Image>` component:

<img width="675" alt="Fullscreen_7_10_23__1_27_PM" src="https://github.com/thumbtack/thumbprint/assets/880266/42898933-8293-4a5b-a6e8-b0152103f4ec">

**Comment by egoens** [comment]
@danoc any thoughts on this? We use the `style` attribute in the [layout.tsx file](https://github.com/thumbtack/thumbprint/blob/master/next/components/layout/layout.tsx#L56) I do not see the TS error locally. I also don't see the issue in the `frontend` repo when making changes to existing `Image` imports.

**Comment by dcapo** [comment]
The `Image` import in layout.tsx is for `next/image`, not the thumbprint `<Image>`. I can't find any usage of the thumbprint `<Image>` in a tsx file in the frontend repo (other than the one I just added in [review-item-photos.tsx](https://github.com/thumbtack/frontend/blob/6e44ddeeb7413aa04b2c905b961be3f6d5b9794d/admin-ui/page-components/reviews/review-item-photos.tsx#L17)).

**Comment by danoc** [comment]
Thanks for the report. I made a fix for it in #944.
