### ISSUE TITLE
Move tokens @import in `thumbprint-global-css` to the root file

### ISSUE THREAD

**Issue by tomgenoni** [thumbtack/thumbprint#95]
Currently is included in each file that needs it. Should be:

```
@import '../node_modules/@thumbtack/thumbprint-tokens/dist/scss/_index';

@import 'packages/_reset';
@import 'packages/_body';
@import 'packages/_a';
```

**Comment by danoc** [comment]
Why use within each file? Seems more clear to import in each file rather than relying on the cascade.

**Comment by tomgenoni** [comment]
I guess it's a philosophical question. Unlike the previous separate SCSS bundles these partials would never be accessed or rendered independently and are only in separate files for convenience. I suppose the same would logic would apply to `thumbprint-atomic` and `thumbprint-scss`. The `dist` is all we care about, no?

One minor issue is that  if `functions` is accidentally not included in a file `tp-spacer(1)` will not return an error but will output the string `tp-spacer(1)` as the value. We should catch that in the snapshots but it wouldn't have happened if it were always included at the root. 

But I don't have strong feels about it and can add them in where needed since that's the convention we've used.

**Comment by danoc** [comment]
Ok cool, I also don't feel strongly here. Happy w/ whichever way you prefer. 👍

**Comment by tomgenoni** [comment]
Ok, I'll leave them in file.
